version: "2"

services:

  record:
    build: .
    restart: unless-stopped
    ports:
      - "5040:5000"
    volumes:
      - /srv/workflow/cfs:/storage



# volumes:
#   # Storage for attachments
#   steedos-storage-1: